### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by songproducer** [jokenox/Goopt#4]
```
Starting the development server...

/Users/leotreasure/Goopt/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/leotreasure/Goopt/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/leotreasure/Goopt/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/leotreasure/Goopt/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/leotreasure/Goopt/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/leotreasure/Goopt/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/leotreasure/Goopt/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/leotreasure/Goopt/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/leotreasure/Goopt/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jokenox** [comment]
Have you already tried running it with the LTS version of Node.js?
